name: Harshitha Chakravarthy Rajappa
favicon: null
layout_spectrum: 1
typography_spectrum: 0.36441
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffff5'
    - '#121711'
    - '#b4641d'
    - '#6d402d'
    - '#940521'
  brandStrength: 0.6276378030888736
  lightness: 0.4375
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
