name: Harshitha Chakravarthy Rajappa
favicon: null
layout_spectrum: 0.1674337920267135
typography_spectrum: 0.6390339664649218
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.6276378030888736
  lightness: 0.24575421819463372
  saturation: 0.9153244467452168
  rhythmicContrast: 0.17398805380798876
purpose: []
